# .reviewer-config.sh — claude-code-reviewer configuration
# Generated by install.sh on 2026-04-10
# Edit to match your project. Source: https://github.com/jazzsequence/claude-code-reviewer

REVIEWER_TEST_CMD="npm run test"
REVIEWER_LINT_CMD="npm run lint"
REVIEWER_BUILD_CMD="npm run build"
REVIEWER_E2E_CMD="npm run test:e2e"

REVIEWER_MAX_FILES=5
REVIEWER_MAX_RENAMES=10
REVIEWER_MAX_INSERTIONS=500
REVIEWER_APPROVAL_TIMEOUT=300
REVIEWER_APPROVAL_FILE="reviewer-approved"

REVIEWER_TEXT_ONLY_PATTERN='\.(md|txt|rst)$'
REVIEWER_EXCLUDED_FILES='^package-lock\.json$|^yarn\.lock$|^pnpm-lock\.yaml$|^composer\.lock$|^Gemfile\.lock$'
